on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  action_tests:
    runs-on: ${{ matrix.os }}
    name: Action Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        cmake_ver: ['', '3.19.3', '3.15.1', '2.8']

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup cmake
      uses: ./
      id: setup
      with:
        cmake-version: ${{ matrix.cmake_ver }}

    - name: Run cmake --version
      shell: bash
      if: matrix.cmake_ver != ''
      run: |
        VERSION=`cmake --version`
        echo $VERSION
        [[ "$VERSION" =~ "${{ matrix.cmake_ver }}" ]]

    - name: Run cmake --version
      # [[ "$VERSION" =~ "" ]] does not work as expected on macos, so don't
      # do the test when using the latest cmake version
      shell: bash
      if: matrix.cmake_ver == ''
      run: |
        VERSION=`cmake --version`
        echo $VERSION

  unit_tests:
    runs-on: ${{ matrix.os }}
    name: Unit Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1

    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      run: bun install

    - name: Run checks and tests
      run: |
        bun run format
        git diff --quiet src/ __tests__/
        bun run package
        git diff --quiet dist/
        bun run test
